const Pedals = [
    {
        id:1,
        name: "Blues Drive BD-2",
        brand: "Boss",
        fxs: ["all","overdrive"],
        description: "Bluesy sounds with a wide range of nuances.",
        url_img: "./img/pedals/bd2-boss.png",
        price: 43000,
        free_shipping: false,
        stock: 0,
    },
    {
        id:2,
        name: "Carbon Copy",
        brand: "MXR",
        fxs: ["all","delay"],
        description: "Classic delay, ideal if you want to go for the safe option.",
        url_img: "./img/pedals/carboncopy.png",
        price: 70000,
        free_shipping: true,
        stock: 4,
    },
    {
        id:3,
        name: "Chorus Ensemble CE-5",
        brand: "Boss",
        fxs: ["all", "modulation"],
        description: "Classic pedal with beautiful angelic sounds.",
        url_img: "./img/pedals/ce5-boss.png",
        price: 35000,
        free_shipping: false,
        stock: 3,
    },
    {
        id:4,
        name: "Compression Sustainer CS-3",
        brand: "Boss",
        fxs: ["all", "compressor"],
        description: "Smooth sustain without degrading the original sound quality.",
        url_img: "./img/pedals/cs3-boss.png",
        price: 41000,
        free_shipping: false,
        stock: 4,
    },
    {
        id:5,
        name: "Repeater",
        brand: "Mooer",
        fxs: ["all", "delay"],
        description: "Basic clean delay effects, natural and clear.",
        url_img: "./img/pedals/delay-mooer.png",
        price: 26000,
        free_shipping: false,
        stock: 7,
    },
    {
        id:6,
        name: "Turbo Distortion DS-2",
        brand: "Boss",
        fxs: ["all", "distortion"],
        description: "Provides biting distortion with a mid-range boost, perfect for leads.",
        url_img: "./img/pedals/ds2-boss.png",
        price: 32000,
        free_shipping: false,
        stock: 3,
    },
    {
        id:7,
        name: "Dyna Comp",
        brand: "MXR",
        fxs: ["all", "compressor"],
        description: "One of the most popular compressors of all time.",
        url_img: "./img/pedals/dynacomp.png",
        price: 42000,
        free_shipping: false,
        stock: 4,
    },
    {
        id:8,
        name: "Green Mile",
        brand: "Mooer",
        fxs: ["all", "overdrive"],
        description: "Provides a natural, smooth, creamy overdrive sound.",
        url_img: "./img/pedals/green-mile.png",
        price: 25000,
        free_shipping: false,
        stock: 6,
    },
    {
        id:9,
        name: "Analog Delay",
        brand: "Joyo",
        fxs: ["all", "delay"],
        description: "Get that mild and mellow circuit delay. True bypass design.",
        url_img: "./img/pedals/joyo-analog-delay.png",
        price: 23000,
        free_shipping: false,
        stock: 5,
    },
    {
        id:10,
        name: "Us Dream",
        brand: "Joyo",
        fxs: ["all", "distortion"],
        description: "Joyo US Dream's purple exterior reminds us of the Suhr Riot distortion pedal.",
        url_img: "./img/pedals/joyo-us-dream.png",
        price: 26000,
        free_shipping: false,
        stock: 3,
    },
    {
        id:11,
        name: "Micro Amp",
        brand: "MXR",
        fxs: ["all", "overdrive", "others"],
        description: "Designed to add a preset amount of gain to your signal using one single control.",
        url_img: "./img/pedals/micro-amp-mxr.png",
        price: 40000,
        free_shipping: true,
        stock: 2,
    },
    {
        id:12,
        name: "Analog Chorus",
        brand: "MXR",
        fxs: ["all", "modulation"],
        description: "This all-analog pedal uses bucket-brigade circuitry to create classically lush, liquid textures.",
        url_img: "./img/pedals/mxr-analog-chorus.png",
        price: 35000,
        free_shipping: true,
        stock: 4,
    },
    {
        id:13,
        name: "Distortion +",
        brand: "MXR",
        fxs: ["all", "distortion"],
        description: "Responsible for those great distortion sounds heard on so many classic recordings.",
        url_img: "./img/pedals/mxr-distortion.png",
        price: 55000,
        free_shipping: true,
        stock: 4,
    },
    {
        id:14,
        name: "Noise Clamp",
        brand: "MXR",
        fxs: ["all","others"],
        description: "Eliminates hiss & excess noise from your effects chain.",
        url_img: "./img/pedals/noise-clamp-mxr.png",
        price: 42500,
        free_shipping: true,
        stock: 2,
    },
    {
        id:15,
        name: "Dual Delay",
        brand: "NUX",
        fxs: ["all","delay"],
        description: "Real stereo delay pedal with independent time / sub-division & repeat knobs.",
        url_img: "./img/pedals/nux-dual-delay.png",
        price: 76500,
        free_shipping: true,
        stock: 0,
    },
    {
        id:16,
        name: "Horse Man",
        brand: "NUX",
        fxs: ["all","overdrive"],
        description: "NUX Horseman pays homage to the legendary Centaur pedal.",
        url_img: "./img/pedals/nux-overdrive.png",
        price: 76500,
        free_shipping: true,
        stock: 0,
    },
    {
        id:17,
        name: "Overdrive/Distortion OS-2",
        brand: "Boss",
        fxs: ["all","overdrive", "distortion"],
        description: "The OS-2 gives players a choice of overdrive or distortion or lets them combine both.",
        url_img: "./img/pedals/os2-boss.png",
        price: 29500,
        free_shipping: false,
        stock: 4,
    },
    {
        id:18,
        name: "Phase 90",
        brand: "MXR",
        fxs: ["all","modulation"],
        description: "Takes you from subtle, spatial shimmer to all-out high velocity swooshing with the twist of a knob.",
        url_img: "./img/pedals/phase90-mxr.png",
        price: 74000,
        free_shipping: true,
        stock: 2,
    },
    {
        id:19,
        name: "Phase 100",
        brand: "MXR",
        fxs: ["all","modulation"],
        description: "With both a Speed control and a 4-waveform Intensity control, the Phase 100 offers a broad range of sounds.",
        url_img: "./img/pedals/phase100-mxr.png",
        price: 79000,
        free_shipping: true,
        stock: 0,
    },
    {
        id:20,
        name: "Reecho",
        brand: "Mooer",
        fxs: ["all","delay"],
        description: "This is a gorgeous soft echo, that isn't harsh like other digital delays, nor grainy like analog mode.",
        url_img: "./img/pedals/reecho-mooer.png",
        price: 28000,
        free_shipping: false,
        stock: 5,
    },
    {
        id:21,
        name: "Super Overdrive SD-1",
        brand: "Boss",
        fxs: ["all","overdrive"],
        description: "Produces the warm, natural distortion of an overdriven tube amp.",
        url_img: "./img/pedals/sd1-boss.png",
        price: 39000,
        free_shipping: false,
        stock: 8,
    },
    {
        id:22,
        name: "Tubescreamer TS-9",
        brand: "Ibanez",
        fxs: ["all","overdrive"],
        description: "Plug it in, crank it up, and you'll hear what all the fuss is about.",
        url_img: "./img/pedals/tubescreamer-ts9-ibanez.png",
        price: 45000,
        free_shipping: false,
        stock: 2,
    },
    {
        id:23,
        name: "Shimverb",
        brand: "Mooer",
        fxs: ["all","reverb"],
        description: "Offers different sized acoustic reverbs.",
        url_img: "./img/pedals/shimverb_mooer.png",
        price: 24000,
        free_shipping: false,
        stock: 3,
    },
]